RAW_DATA_FOLDER = "./Raw Data/"
CLEANED_DATA_FILEPATH = "./Clean Data/CleanData.csv"
NORMALIZED_DATA_FILEPATH = "./Normalized Data/NormalizedData.csv"
DECISION_TREE_GRAPHS_FILEPATH = "./Decision Tree Graphs/"
CORRELATION_ANALYSIS_FILEPATH = "./Correlation Analysis Results.csv"
