RAW_DATA_FOLDER = "./Raw Data/"
CLEANED_DATA_FILEPATH = "./Processed Data/CleanData.csv"
NORMALIZED_DATA_FILEPATH = "./Processed Data/NormalizedData.csv"
DECISION_TREE_GRAPHS_FILEPATH = "./Learned Data/Decision Tree Graphs/"
CORRELATION_ANALYSIS_FILEPATH = "./Learned Data/Correlation Analysis Results.csv"
